### ISSUE TITLE
traitsui 6.0.0-1 doesn't work

### ISSUE THREAD

**Issue by syou83syou83** [alexlib/pyptv#21]
The traitsui 6.0.0-1 doesn't work for pyptv. It sends error messages of missing argements when I do "3D positions" or "Sequence without play". Traitsui 5.1.0-2 wroks fine.

**Comment by alexlib** [comment]
I think it was relevant for Python 2.7 - we have Python 3 in action now and it should work. @syou83syou83 - can you please test again?
