### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by aeba402** [alexlib/pyptv#47]
Hi Alex

The link http://www.mediafire.com/file/c820cww6b7styzq/openptv.ova/file to download the PyPTV virtual machine image is not working. Can you please upload the correct link once more? Thanks.

**Comment by alexlib** [comment]
we should remove this option @aeba402 - this is not a recommended way of installing the software, please follow the instructions on our documentation website

**Comment by aeba402** [comment]
Hi Alex

Thanks for your reply. I implemented your recommendation and am working with the pyPTV at the moment on my machine. Cheers.
